version: '3.8'

networks:
  traefik-network:
    name: traefik-network
    driver: bridge

services:
  traefik:
    image: 'traefik:v2.0.0'
    container_name: 'dashboard'
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --api
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - ./certs/:/certs/:ro
      - ./traefik/conf.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    labels:
      - 'traefik.enable=true'
      # Dashboard
      - 'traefik.http.routers.traefik.rule=Host(`dashboard.${DOMAIN}`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      # - 'traefik.http.routers.traefik.middlewares=authtraefik'
      # - 'traefik.http.middlewares.authtraefik.basicauth.users=user:pass' # user/password
      # global redirect to https
      - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.entrypoints=web'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
      # middleware redirect
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
    networks:
      - traefik-network
