version: '2.3'

networks:
  {{NETWORK_NAME}}:
    external: true

services:
  {{APP}}-code-server:
    image: 'codeman-demo:latest'
    runtime: nvidia
    container_name: {{APP}}-code-server
    environment:
      - PASSWORD=123456
      - 'DISPLAY={{APP}}-novnc:0.0'
      - NVIDIA_VISIBLE_DEVICES=all
    user: 1000:1000
    labels:
      - 'code-server'
      - 'traefik.enable=true'
      - 'traefik.http.services.{{APP}}-code-server.loadbalancer.server.port=8080'
      - 'traefik.http.routers.{{APP}}-code-server.rule=Host(`{{APP}}-code-server.${DOMAIN}`)'
      # - 'traefik.http.routers.my-app.middlewares=auth'
      - 'traefik.http.routers.{{APP}}-code-server.entrypoints=websecure'
      - 'traefik.http.routers.{{APP}}-code-server.tls=true'
      # - 'traefik.http.middlewares.auth.basicauth.users=user:pass' # user/password
    networks:
      - ${NETWORK_NAME}
  {{APP}}-novnc:
    image: 'theasp/novnc:latest'
    container_name: {{APP}}-novnc
    environment:
      - 'DISPLAY_WIDTH=1024'
      - 'DISPLAY_HEIGHT=768'
      - 'RUN_XTERM=no'
      - 'RUN_FLUXBOX=yes'
    labels:
      - 'novnc'
      - 'traefik.enable=true'
      - 'traefik.http.services.{{APP}}-novnc.loadbalancer.server.port=8080'
      - 'traefik.http.routers.{{APP}}-novnc.rule=Host(`{{APP}}-novnc.${DOMAIN}`)'
      # - 'traefik.http.routers.my-app.middlewares=auth'
      - 'traefik.http.routers.{{APP}}-novnc.entrypoints=websecure'
      - 'traefik.http.routers.{{APP}}-novnc.tls=true'
      # - 'traefik.http.middlewares.auth.basicauth.users=user:pass' # user/password
    networks:
      - ${NETWORK_NAME}