version: '3.8'

networks:
  {{NETWORK_NAME}}:
    external: true

services:
  {{APP}}-whoami:
    image: emilevauge/whoami
    container_name: {{APP}}-whoami
    labels:
      - 'code-server'
      - 'traefik.enable=true'
      - 'traefik.http.routers.{{APP}}-code-server.rule=Host(`{{APP}}-code-server.${DOMAIN}`)'
      # - 'traefik.http.routers.my-app.middlewares=auth'
      - 'traefik.http.routers.{{APP}}-code-server.entrypoints=websecure'
      - 'traefik.http.routers.{{APP}}-code-server.tls=true'
      # - 'traefik.http.middlewares.auth.basicauth.users=user:pass' # user/password
    networks:
      - ${NETWORK_NAME}